---
title: "Capstone-Project-FS23-for-R-Datamining-Class"
output: html_document
---
This Capstone project is about mapping and displaying the whereabouts of the “Fahrende”, a nomadic people in Switzerland.

Overall, there are about 30,000 people of Yenish origin, plus a few hundred Sinti and Manouches, of whom an estimated minority of 2,000 to 3,000 people still live a nomadic lifestyle: In winter they live on a “Standplatz” and from spring to fall they are "on the road" with their caravans, stopping at transit sites and visiting their customers. During this time, the children have their homework assignments forwarded to them by their regular school and send them back to the teachers for correction. As Swiss citizens they have the same rights and duties as the settled population. The Yenish and Sinti have been part of Switzerland's cultural diversity for centuries.
Regular surveys conducted by the foundation "Zukunft Schweizer Fahrende" show that the number of available “Stand-“, “Durchgangs-“ and “Transitplätze” has decreased dramatically. This applies to most regions, but particularly affects western, eastern and southern Switzerland. The search for stopping places for Yenish, Sinti and Roma on the journey is increasingly difficult. The pressure of use on the rare free areas in the suburbs has increased, the needs of the traveling minorities are often the last to be considered or unsuitable sites are offered.
Through sensitization and education, the understanding of the travelling way of life is to be promoted and the reduction of prejudices and fears is to be contributed to. Secondly, the concerns of minorities must be taken into account in spatial planning.

The data and graphs generated by this project are hopefully to be used as a starting point for a future research project into the lives and culture of the “Fahrende”. 

I began my research by stumbling upon a Dataset of the “Standplätze, Durchgangs- und Transitplätze für Jenische, Sinti und Roma” on Opendata.swiss, a platform with a wide range of opensource datasets, including publicly available APIs, provided by the Swiss Government. The URL was: https://opendata.swiss/en/dataset/standplatze-durchgangs-und-transitplatze-fur-jenische-sinti-und-roma. 
Having always wanted to learn more about the lives and culture of these people, I decided to investigate the matter closer. The dataset contained a number of geolocation data points (location, exact address, coordinates) and some specifications about the location itself (status, kind of spot, and capacity for caravans). Feeling that this dataset would be about the right size for a beginner, I tagged the URL and went to work.
First, I had to reconnect R Studio with my Github Repository, as I already had some trouble in the past, setting it up in a correct manner. I suppose this has something to do with being unable to install Homebrew and instead having to rely on the system internal version of GitHub on Macos. This is documented in the “Reset Git.R” script.
Then, I tried to extract and parse the data from the API (https://api3.geo.admin.ch/rest/services/api/MapServer/ch.bak.halteplaetze-jenische_sinti_roma). Unfortunately, I could never get it to work for two major reasons:
1. There were too many unsolvable error messages. Furthermore, the list that the API gave out, were structured in a weird manner. The columns were ordered in rows and the values that are supposed to be ordered in rows are arranged in a single cell. This made extracting and parsing the data in the way, that I wanted impossible. I tried several approaches and looked for help, both by looking at code from earlier assignments and lecture material, as well as trying out suggestions from ChatGPT 3.5, but ultimately to no avail.
2.	As I more closely started to inspect the API during that process, I realized that it only contained 5 of the overall 45 elements, that I wanted to inspect. This was probably the bigger problem in the end, of why I was unable to correctly extract and parse the information.
This process and the troubles with it were documented in the comments of the “API Setup.R” Script.
Fortunately, the URL also contained an Excel File with which I could continue my work. (Available here: https://data.geo.admin.ch/browser/index.html#/collections/ch.bak.halteplaetze-jenische_sinti_roma/items/halteplaetze-jenische_sinti_roma?.asset=asset-halteplaetze-jenische_sinti_roma_2056.xlsx.zip). 
With the “readxl” package I was able to read the data into R Studio. What proved difficult however, was to push the Excel file onto the GitHub Repo into the correct folder. My code did not work, and I ended up having to manually save the file on my Repo and then push it to Github via Commit + Push on R Studio, where it isn’t in the proper “data” folder and on the main instead. After removing some missing values from the table, the data preparation was done, and I could proceed with my actual work. For more details, refer to the “Data Preparation.R” script. For more details, consider the “Data Preparation.R” script.

My main work consists of three scripts: “Spatial Analysis.R”, “Descriptive Stats.R”, and “Data Visualization.R”.
In the Spatial Analysis Script, I accomplished several tasks. I tried to calculate the distance between each spot and identify clusters, as well as showcasing which cantons have the most locations and the most available spots for caravans. Furthermore, I created a distance matrix, which shows the distance between each location, and I created a scatter plot of 4 clusters. The generated data and plots can be found in the “Data” and the “Images” folder.
In the Descriptive Statistics Script, I conducted some basic statistics, that are supposed to put some of the numbers into perspective.
In the Data Visualization Script, I managed (after repeatedly trying) to underlie a map of Switzerland under the data of three different plots:
1.	The first map shows the locations, the kind of spot and its status.
2.	The second map shows not only the last two attributes, but also its approximate size.
3.	The third map shows the 4 location clusters from the spatial analysis, but with a map.
The Maps can be found in the “Images” folder. The great difficulties partially stemmed from encoding errors, for which some of the columns had to be renamed, different coordination systems, which had to be converted and the Google Maps API, which initially worked, but then stopped (probably due to not having paid their fees). I solved this problem by later switching to Openstreet Map, which ultimately worked just fine. Some of these errors can be viewed in the “Faulty Code Appendix + Suggestions.R” Script.


